#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo ''
echo 'Inicio do pre-commit.'
echo ''
yarn lint-staged
echo ''
echo 'Inicio do test.'
echo '#Sem testes no momento'
# yarn test
echo ''
echo 'Fim do test.'
echo 'Fim do pre-commit.'
echo ''
